### ISSUE TITLE
Restrict input chars

### ISSUE THREAD

**Issue by kleinph** [lekoala/cleave-es6#1]
Feature Request: make it possible to specify the allowed characters for the input, like numbers or letters.

See also issue in cleave.js: https://github.com/nosir/cleave.js/issues/680

Thanks

**Comment by lekoala** [comment]
here you go
https://github.com/lekoala/cleave-es6/releases/tag/1.0.1

**Comment by kleinph** [comment]
Thanks for the quick implementation!

Did a quick test and found a bug: when a string with unallowed chars is pasted into the input no formatting is applied.
Since I couldn't find a demo with the `allowedChars` property, I made a small reproducers: https://stackblitz.com/edit/js-5dbedx

**Comment by lekoala** [comment]
oh i see

fixed in https://github.com/lekoala/cleave-es6/releases/tag/1.0.2

**Comment by kleinph** [comment]
Thanks, it seems fixed now.
