### ISSUE TITLE
Change blocks depending on input

### ISSUE THREAD

**Issue by kleinph** [lekoala/cleave-es6#2]
Is it possible to change the blocks based on the current input?

In cleave.js this could be achieved by destroying the Cleave instance and initializing a new one with updated config. Since cleave-es6 only exposes the custom element and not the constructor this is not possible.

Updating the data-config property also has no effect.

I made a small example to better showcase what I want to achieve: https://stackblitz.com/edit/js-t5repw

**Comment by lekoala** [comment]
@kleinph reinit seems like overkill for the task :-)

you can do it like so, but i've also added a setBlocks method that is much more elegant. don't forget you can get the instance from the element using getCleave

                    const inst = el.getCleave();

                    // Update config with new blocks.
                    inst.setBlocks(blocks);

                    // Update data-config with new blocks.
                    // el.dataset.config = JSON.stringify({
                    //     ...config,
                    //     blocks,
                    // });
                    // el.init();

https://github.com/lekoala/cleave-es6/releases/tag/1.0.3

**Comment by lekoala** [comment]
closing, feel free to reopen if you need something else

**Comment by kleinph** [comment]
Thanks again for implementing this so quickly!

I noticed one small problem: 
- enter _AT00 3333 3333 0000 1111_ 
- change _AT_ to _BE_
- the last block (_1111_) remains, altough I would expect it to be cut off

PS: Sorry for the late reply, I was on vaction.

**Comment by lekoala** [comment]
@kleinph yes, you can of course run formatInput(el.value) just after that, but it's not ideal. in fact, the block should change before the formatting itself (listening on input does it after)

i added two hooks : beforeInput and afterInput and corresponding events. They allow you to adjust things better (and it works also for copy paste for example)

            const BLOCKS = {
                    AT: [4, 4, 4, 4, 4],
                    BE: [4, 4, 4, 4],
                    __: [4, 4, 4, 4, 4, 4, 4, 4, 2],
                };

                const el = document.getElementById('variable-input-el');
                const config = JSON.parse(el.dataset.config);

                el.addEventListener('cleave.valuechanged', (ev) => {
                    console.log("value changed", ev.detail)
                })

                el.addEventListener('cleave.beforeinput', (ev) => {
                    // Determine blocks based on first two characters.
                    const code = event.target.value.slice(0, 2) || '__';
                    const blocks = BLOCKS[code] ?? BLOCKS['__'];

                    const inst = el.getCleave();
                    inst.setBlocks(blocks);
                });
